substitutions:
  _REGION: "asia-northeast3"
  _ARTIFACT_REPO: "my-repo"
  _FRONTEND_BUCKET: "frontend-bucket-001"
  _FRONTEND_SERVICE: "frontend-service"
  _BACKEND_SERVICE: "backend-service"
  _BACKEND_SA: "backend-sa@samsung-mx-test.iam.gserviceaccount.com"

steps:
# 1) Frontend build
- name: 'node:18'
  id: 'frontend:install'
  dir: 'frontend'
  args: ['bash','-lc','npm install']

- name: 'node:18'
  id: 'frontend:build'
  dir: 'frontend'
  args: ['bash','-lc','npm run build']

# 2) Frontend Docker build
- name: 'gcr.io/cloud-builders/docker'
  id: 'frontend:docker_build'
  dir: 'frontend'
  args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}','.']

# 3) Frontend Docker push
- name: 'gcr.io/cloud-builders/docker'
  id: 'frontend:docker_push'
  args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}']

# 4) Deploy frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'frontend:deploy'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_FRONTEND_SERVICE}'
    - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'

# 5) Backend build (maven)
- name: 'maven:3.9-eclipse-temurin-17'
  id: 'backend:mvn'
  dir: 'backend'
  args: ['mvn','-B','package','-DskipTests']

# 6) Backend Docker build
- name: 'gcr.io/cloud-builders/docker'
  id: 'backend:docker_build'
  dir: 'backend'
  args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend:${SHORT_SHA}','.']

# 7) Backend Docker push
- name: 'gcr.io/cloud-builders/docker'
  id: 'backend:docker_push'
  args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend:${SHORT_SHA}']

# 8) Deploy backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'backend:deploy'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_BACKEND_SERVICE}'
    - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend:${SHORT_SHA}'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--service-account=${_BACKEND_SA}'
    - '--allow-unauthenticated'
    - '--set-env-vars=PROJECT_ID=$PROJECT_ID,vertex.location=${_REGION},gcs.output.bucket=${_FRONTEND_BUCKET}'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
